services:
  eniqilo-store-api:
      container_name: eniqilo-store-api
      image: eniqilo-store-api:latest
      build:
        context: .
        dockerfile: Dockerfile
      env_file:
        - .env
      restart: unless-stopped
      ports:
        - 0.0.0.0:8080:8080
      extra_hosts:
      - "host.docker.internal:host-gateway"