package constant

var CountryCode = map[string]string{
	"United States":                    "+1",
	"China":                            "+86",
	"Japan":                            "+81",
	"Germany":                          "+49",
	"Brazil":                           "+55",
	"France":                           "+33",
	"Italy":                            "+39",
	"Russia":                           "+7",
	"United Kingdom":                   "+44",
	"Australia":                        "+61",
	"Canada":                           "+1",
	"India":                            "+91",
	"Mexico":                           "+52",
	"South Korea":                      "+82",
	"Spain":                            "+34",
	"Indonesia":                        "+62",
	"Turkey":                           "+90",
	"Netherlands":                      "+31",
	"Saudi Arabia":                     "+966",
	"Switzerland":                      "+41",
	"Sweden":                           "+46",
	"Norway":                           "+47",
	"Poland":                           "+48",
	"Belgium":                          "+32",
	"Nigeria":                          "+234",
	"Argentina":                        "+54",
	"Taiwan":                           "+886",
	"Austria":                          "+43",
	"Iran":                             "+98",
	"Thailand":                         "+66",
	"United Arab Emirates":             "+971",
	"Colombia":                         "+57",
	"Venezuela":                        "+58",
	"South Africa":                     "+27",
	"Denmark":                          "+45",
	"Malaysia":                         "+60",
	"Singapore":                        "+65",
	"Chile":                            "+56",
	"Hong Kong":                        "+852",
	"Israel":                           "+972",
	"Philippines":                      "+63",
	"Egypt":                            "+20",
	"Finland":                          "+358",
	"Greece":                           "+30",
	"Pakistan":                         "+92",
	"Kazakhstan":                       "+7",
	"Iraq":                             "+964",
	"Ireland":                          "+353",
	"Portugal":                         "+351",
	"Algeria":                          "+213",
	"Qatar":                            "+974",
	"Peru":                             "+51",
	"Czech Republic":                   "+420",
	"Romania":                          "+40",
	"New Zealand":                      "+64",
	"Kuwait":                           "+965",
	"Ukraine":                          "+380",
	"Vietnam":                          "+84",
	"Bangladesh":                       "+880",
	"Hungary":                          "+36",
	"Angola":                           "+244",
	"Morocco":                          "+212",
	"Slovakia":                         "+421",
	"Puerto Rico":                      "+1-787",
	"Puerto Rico1":                     "+1-939",
	"Ecuador":                          "+593",
	"Oman":                             "+968",
	"Azerbaijan":                       "+994",
	"Cuba":                             "+53",
	"Libya":                            "+218",
	"Belarus":                          "+375",
	"Sri Lanka":                        "+94",
	"Syria":                            "+963",
	"Luxembourg":                       "+352",
	"Croatia":                          "+385",
	"Dominican Republic":               "+1-809",
	"Dominican Republic1":              "+1-829",
	"Dominican Republic2":              "+1-849",
	"Myanmar":                          "+95",
	"Uruguay":                          "+598",
	"Uzbekistan":                       "+998",
	"Bulgaria":                         "+359",
	"Guatemala":                        "+502",
	"Sudan":                            "+249",
	"Macau":                            "+853",
	"Costa Rica":                       "+506",
	"Tunisia":                          "+216",
	"Ethiopia":                         "+251",
	"Lithuania":                        "+370",
	"Slovenia":                         "+386",
	"Ghana":                            "+233",
	"Kenya":                            "+254",
	"Lebanon":                          "+961",
	"Serbia":                           "+381",
	"Yemen":                            "+967",
	"Panama":                           "+507",
	"Turkmenistan":                     "+993",
	"Jordan":                           "+962",
	"Tanzania":                         "+255",
	"Bolivia":                          "+591",
	"Latvia":                           "+371",
	"Paraguay":                         "+595",
	"Bahrain":                          "+973",
	"Ivory Coast":                      "+225",
	"North Korea":                      "+850",
	"Cameroon":                         "+237",
	"Trinidad and Tobago":              "+1-868",
	"El Salvador":                      "+503",
	"Estonia":                          "+372",
	"Uganda":                           "+256",
	"Zambia":                           "+260",
	"Cyprus":                           "+357",
	"Afghanistan":                      "+93",
	"Gabon":                            "+241",
	"Nepal":                            "+977",
	"Bosnia and Herzegovina":           "+387",
	"Democratic Republic of the Congo": "+243",
	"Honduras":                         "+504",
	"Equatorial Guinea":                "+240",
	"Brunei":                           "+673",
	"Papua New Guinea":                 "+675",
	"Botswana":                         "+267",
	"Cambodia":                         "+855",
	"Georgia":                          "+995",
	"Senegal":                          "+221",
	"Iceland":                          "+354",
	"Jamaica":                          "+1-876",
	"Mozambique":                       "+258",
	"Republic of the Congo":            "+242",
	"Chad":                             "+235",
	"Albania":                          "+355",
	"Burkina Faso":                     "+226",
	"Namibia":                          "+264",
	"Mali":                             "+223",
	"Mauritius":                        "+230",
	"Mongolia":                         "+976",
	"Nicaragua":                        "+505",
	"South Sudan":                      "+211",
	"Armenia":                          "+374",
	"Laos":                             "+856",
	"Macedonia":                        "+389",
	"Madagascar":                       "+261",
	"Zimbabwe":                         "+263",
	"Malta":                            "+356",
	"New Caledonia":                    "+687",
	"Bahamas":                          "+1-242",
	"Benin":                            "+229",
	"Haiti":                            "+509",
	"Tajikistan":                       "+992",
	"Kosovo":                           "+383",
	"Kyrgyzstan":                       "+996",
	"Moldova":                          "+373",
	"Niger":                            "+227",
	"Rwanda":                           "+250",
	"East Timor":                       "+670",
	"Guinea":                           "+224",
	"Palestine":                        "+970",
	"Bermuda":                          "+1-441",
	"Curacao":                          "+599",
	"French Polynesia":                 "+689",
	"Jersey":                           "+44-1534",
	"Liechtenstein":                    "+423",
	"Monaco":                           "+377",
	"Suriname":                         "+597",
	"Andorra":                          "+376",
	"Barbados":                         "+1-246",
	"Fiji":                             "+679",
	"Guam":                             "+1-671",
	"Isle of Man":                      "+44-1624",
	"Mauritania":                       "+222",
	"Montenegro":                       "+382",
	"Sierra Leone":                     "+232",
	"Togo":                             "+228",
	"Eritrea":                          "+291",
	"Guyana":                           "+592",
	"Malawi":                           "+265",
	"Swaziland":                        "+268",
	"Aruba":                            "+297",
	"Bhutan":                           "+975",
	"Burundi":                          "+257",
	"Cayman Islands":                   "+1-345",
	"Central African Republic":         "+236",
	"Faroe Islands":                    "+298",
	"Greenland":                        "+299",
	"Guernsey":                         "+44-1481",
	"Lesotho":                          "+266",
	"Maldives":                         "+960",
	"Somalia":                          "+252",
	"Antigua and Barbuda":              "+1-268",
	"Belize":                           "+501",
	"British Virgin Islands":           "+1-284",
	"Cape Verde":                       "+238",
	"Djibouti":                         "+253",
	"Gibraltar":                        "+350",
	"Liberia":                          "+231",
	"Saint Lucia":                      "+1-758",
	"San Marino":                       "+378",
	"Seychelles":                       "+248",
	"Solomon Islands":                  "+677",
	"Gambia":                           "+220",
	"Guinea-Bissau":                    "+245",
	"Vanuatu":                          "+678",
	"Grenada":                          "+1-473",
	"Sint Maarten":                     "+1-721",
	"Saint Kitts and Nevis":            "+1-869",
	"Saint Vincent and the Grenadines": "+1-784",
	"Northern Mariana Islands":         "+1-670",
	"Samoa":                            "+685",
	"Comoros":                          "+269",
	"Saint Martin":                     "+590",
	"Dominica":                         "+1-767",
	"Tonga":                            "+676",
	"American Samoa":                   "+1-684",
	"Micronesia":                       "+691",
	"Sao Tome and Principe":            "+239",
	"Palau":                            "+680",
	"Saint Pierre and Miquelon":        "+508",
	"Marshall Islands":                 "+692",
	"Cook Islands":                     "+682",
	"Anguilla":                         "+1-264",
	"Kiribati":                         "+686",
	"Falkland Islands":                 "+500",
	"Tuvalu":                           "+688",
	"Niue":                             "+683",
	"Antarctica":                       "+672",
	"British Indian Ocean Territory":   "+246",
	"Christmas Island":                 "+61",
	"Cocos Islands":                    "+61",
	"Mayotte":                          "+262",
	"Montserrat":                       "+1-664",
	"Nauru":                            "+674",
	"Netherlands Antilles":             "+599",
	"Pitcairn":                         "+64",
	"Reunion":                          "+262",
	"Saint Barthelemy":                 "+590",
	"Saint Helena":                     "+290",
	"Svalbard and Jan Mayen":           "+47",
	"Tokelau":                          "+690",
	"Turks and Caicos Islands":         "+1-649",
	"U.S. Virgin Islands":              "+1-340",
	"Vatican":                          "+379",
	"Wallis and Futuna":                "+681",
	"Western Sahara":                   "+212",
}
